### ISSUE TITLE
Change docker-compose now that Airflow 2.0 has been released

### ISSUE THREAD

**Issue by saveriogzz** [zahiar/apache-airflow-playground#1]
Hi!
Thank you for your work here.

I'm trying to figuring out how to swap to the official airflow 2.0 docker image now that has been released but I'm not sure which one to pick.. any suggestions?

Cheers

**Comment by zahiar** [comment]
Hi @saveriogzz, I've just updated the docker-compose to use image tag `2.0.0-python3.8`.

There is a much, much larger image tag `2.0.0-python3.8-build` (630MB vs 220MB), which is used to download & build the various components that are used by Airflow, and these are then copied into a new image resulting in a much smaller size (this image is the one that gets tagged without the `-build` suffix - one I'm using).

Honestly, I'd just stick to the smaller, more finalised image - it's clean without any of the cruft used solely to build Airflow, that probably won't get used once Airflow runs - if that makes sense.

As for the version of Python, well I generally prefer to keep at the latest version if possible, but they do have 3.6 `2.0.0-python3.6` & 3.7 `2.0.0-python3.7` if you need to use them.

Hope this helps 🙂

**Comment by saveriogzz** [comment]
Thanks! that's great :)
